@baseUrl = http://localhost:3100
###
GET {{baseUrl}}

###
GET {{baseUrl}}/users/login

###
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "userName": "ShyRobin",
  "password": "test.password"
}