@baseUrl = http://localhost:3100
###
GET {{baseUrl}}

### 登录
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "userName": "Robin3",
  "password": "test"
}

### 注册
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "userName": "Robin",
  "password": "test"
}

### 修改密码
PATCH {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwidXNlck5hbWUiOiJSb2JpbiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NTk5MjM4ODEsImV4cCI6MTY2MDAxMDI4MX0.8xUSb0joMgIskiEJi18Lfxxvgtf2j0mPz-anFKE59S8

{
  "oldPassword": "test",
  "newPassword": "test111"
}

### 上传图片
POST {{baseUrl}}/goods/upload
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwidXNlck5hbWUiOiJSb2JpbjMiLCJpc0FkbWluIjp0cnVlLCJpYXQiOjE2NTk5MzAwMzgsImV4cCI6MTY2MDAxNjQzOH0.tsZ4xAz-waPjLmOPcDJ9MB-oF2R0ZHRo8t0bMdaa34E
