@baseUrl = http://localhost:3100
###
GET {{baseUrl}}

### 登录
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "userName": "Robin1",
  "password": "test"
}

### 注册
POST {{baseUrl}}/users/register
Content-Type: application/json

{
  "userName": "Robin1",
  "password": "test"
}

### 修改密码
PATCH {{baseUrl}}/users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlck5hbWUiOiJSb2JpbjEiLCJpc0FkbWluIjpmYWxzZSwiaWF0IjoxNjU5ODc0MzMxLCJleHAiOjE2NTk5NjA3MzF9.KcifZPq63K-BJvGwqmsRjdDAddD2Tmfkez-0ZkjxsW4

{
  "oldPassword": "test1",
  "newPassword": "test"
}